#!/bin/sh

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
    set -x
fi
set -o nounset # avoid use of undefined variables
set -o errexit # fail fast


LUNCHY_DIRS="/Library/LaunchAgents ${HOME}/Library/LaunchAgents /Library/LaunchDaemons /System/Library/LaunchDaemons"
LUNCHY_SUBCOMMAND="$1"
LUNCHY_PATTERN="$2"

lunchy_start() {
    local pfile=$(find $LUNCHY_DIRS -iname "*.plist" | grep -i $LUNCHY_PATTERN)
    local count=$(find $LUNCHY_DIRS -iname "*.plist" | grep -i $LUNCHY_PATTERN |wc -l)

    if [ $count -gt 1 ]; then
      echo "Multiple daemons found matching '$LUNCHY_PATTERN'. You need to be more specific. Matches found are:\n$pfile"
    elif [ $count -lt 1 ]; then
      echo "No daemon found matching '$LUNCHY_PATTERN'"
    else
      echo "launchctl load #{force}#{write} $pfile"
      echo "started $LUNCHY_PATTERN"
    fi
}

lunchy_stop() {
    local pfile=$(find $LUNCHY_DIRS -iname "*.plist" | grep -i $LUNCHY_PATTERN)
    local count=$(find $LUNCHY_DIRS -iname "*.plist" | grep -i $LUNCHY_PATTERN |wc -l)

    if [ $count -gt 1 ]; then
      echo "Multiple daemons found matching '$LUNCHY_PATTERN'. You need to be more specific. Matches found are:\n$pfile"
    elif [ $count -lt 1 ]; then
      echo "No daemon found matching '$LUNCHY_PATTERN'"
    else
      echo "launchctl unload #{force}#{write} $pfile"
      echo "stopped $LUNCHY_PATTERN"
    fi
}

lunchy_restart() {
  lunchy_stop
  lunchy_start
}

main() {
  local subcommand_to_run="lunchy_$LUNCHY_SUBCOMMAND"
  echo $subcommand_to_run
  $subcommand_to_run
}

main
